# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Submit alpha release to Google Play Store"
    lane :alpha do
        increment_version_code(
            gradle_file_path: "./app/build.gradle"
        )
        gradle(task: "assembleRelease")
        supply(
            track: "alpha",
            apk: "#{lane_context[ShareValues:: GRADLE_APK_OUT_PATH]}"
        )
    end

     desc "Submit beta release to Google Play Store"
        lane :beta do
            increment_version_code(
                gradle_file_path: "./app/build.gradle"
            )
            gradle(task: "assembleRelease")
            supply(
                track: "beta",
                apk: "#{lane_context[ShareValues:: GRADLE_APK_OUT_PATH]}"
            )
        end


      desc "Submit production release to Google Play Store"
        lane :production do
            increment_version_code(
                gradle_file_path: "./app/build.gradle"
            )
            gradle(task: "assembleRelease")
            supply(
                track: "production",
                apk: "#{lane_context[ShareValues:: GRADLE_APK_OUT_PATH]}"
            )
            end

end
